[datacapture]
updateInterval = 50

[plotting]
plotXAxisWidth = 40

[logging]
logFilePath = "logs/"

[thresholds]
warningLimits = [
              20,   # Battery current
              70,   # Bus voltage
              135,  # Measured phase current
              215,  # Commanded phase current
              21,   # Speed
              90,   # Throttle output
              205   # Engine temperature
]