[application]
MACAddress = "00:06:66:82:79:5C"
plotWidth = 40
logFilePath = "./logs/" # There must be a slash after the logFilePath
mechPlotMin = -5
mechPlotMax = 5
elecPlotMin = -5
elecPlotMax = 5

[[data]]
name = "Time since engine start"
type = "Time"
colour = "none"
position = 0
multiplier = 1
minWarning = 0
maxWarning = 0

[[data]]
name = "Commanded engine speed"
type = "Mechanical"
colour = "red"
position = 1
multiplier = 1000
minWarning = 0
maxWarning = 7250

[[data]]
name = "Measured engine speed"
type = "Mechanical"
colour = "green"
position = 2
multiplier = 1000
minWarning = 0
maxWarning = 7250

[[data]]
name = "Throttle position"
type = "Mechanical"
colour = "blue"
position = 3
multiplier = 100
minWarning = 0
maxWarning = 100

[[data]]
name = "Bus voltage"
type = "Electrical"
colour = "red"
position = 4
multiplier = 1000
minWarning = 22
maxWarning = 26

[[data]]
name = "Battery current"
type = "Electrical"
colour = "green"
position = 5
multiplier = 1
minWarning = -10
maxWarning = 60

[[data]]
name = "Commanded phase current"
type = "Electrical"
colour = "blue"
position = 6
multiplier = 1
minWarning = 0
maxWarning = 60

[[data]]
name = "Measured phase current"
type = "Electrical"
colour = "black"
position = 7
multiplier = 1
minWarning = 0
maxWarning = 60

[[data]]
name = "Engine state"
type = "CurrentEngineState"
colour = "none"
position = 8
multiplier = 1
minWarning = 0
maxWarning = 0
